version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.9.0

workflows:
  build:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
          - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: "simonpasquier/prometheus-orb"
          publish-token-variable: CIRCLECI_API_TOKEN
          requires:
          - orb-tools/pack

      - orb-tools/increment:
          orb-ref: "simonpasquier/prometheus-orb"
          publish-token-variable: CIRCLECI_API_TOKEN
          checkout: false
          attach-workspace: true
          segment: minor
          requires:
          - orb-tools/pack
          filters:
            branches:
              only: master
