version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.9.0

workflows:
  build:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
          - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: "simonpasquier/prometheus-orb"
          requires:
          - orb-tools/pack

            #      - orb-tools/increment:
            #          orb-path: packed/orb.yml
            #          orb-ref: "simonpasquier/prometheus-orb"
            #          segment: "patch"
            #          publish-token-variable: CIRCLECI_API_TOKEN
            #          attach-workspace: true
            #          checkout: false
            #          requires: [orb-tools/pack]
            #          filters:
            #            branches:
            #              only: master
